name: Reusable label sync workflow

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '0 12 * * *'

jobs:
  sync-labels:
    name: Sync labels 🏷️
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@v2
        with:
          config-file: 'https://raw.githubusercontent.com/kryonitelabs/.github/main/.github/default-labels.yml'
          delete-other-labels: true
          token: ${{ secrets.GITHUB_TOKEN }}
