name: Build and test 🏗️

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.4.0
      - name: Cache gradle related files 🗄️
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK ⚙️
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Building project 🛠️
        run: ./gradlew compileJava
  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Cache gradle related files 🗄️
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK ⚙️
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Running Checkstyle 🧪
        run: ./gradlew checkstyleMain checkstyleTest
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Cache gradle related files 🗄️
        uses: actions/cache@v2.1.7
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache SonarCloud packages 🗄️
        uses: actions/cache@v2.1.7
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Set up JDK ⚙️
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Running tests 🧪
        run: ./gradlew test
      - name: Running analysis in SonarCloud 📊
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube